from tkinter import *
def add():
    x=int(ent1.get())
    y=int(ent2.get())
    r=str(x+y)
    result.delete(0,END)
    result.insert(0,r)
def sub():
    x=int(ent1.get())
    y=int(ent2.get())
    r=str(x-y)
    result.delete(0,END)
    result.insert(0,r)
def mul():
    x=int(ent1.get())
    y=int(ent2.get())
    r=str(x*y)
    result.delete(0,END)
    result.insert(0,r)
def div():
    x=int(ent1.get())
    y=int(ent2.get())
    r=str(round((x/y),2))
    result.delete(0,END)
    result.insert(0,r)
def clear():
    ent1.delete(0,END)
    ent2.delete(0,END)
    result.delete(0,END)
window = Tk()
window.geometry("500x420")
window.title("Window")
label=Label(window,text="Operator",font=("Comic Sans", 10, "bold"))
label.grid(row=0,column=1,padx=5,pady=5)
equal=Label(window,text="=",font=("Comic Sans", 20, "bold"))
equal.grid(row=0,column=4,padx=5,pady=5)
ent1=Entry(window,font=("Comic Sans", 30, "bold"),width=5)
ent1.grid(row=0,column=0)
ent2=Entry(window,font=("Comic Sans", 30, "bold"),width=5)
ent2.grid(row=0,column=3)
result=Entry(window,font=("Comic Sans", 30, "bold"),width=5)
result.grid(row=0,column=5)
b1=Button(window, text="+",font=("Comic Sans", 20, "bold"),command=add,height=1,width=3)
b1.grid(row=1,column=0)
b2=Button(window, text="-",font=("Comic Sans", 20, "bold"),command=sub,height=1,width=3)
b2.grid(row=1,column=1)
b3=Button(window, text="x",font=("Comic Sans", 20, "bold"),command=mul,height=1,width=3)
b3.grid(row=2,column=0)
b4=Button(window, text="/",font=("Comic Sans", 20, "bold"),command=div,height=1,width=3)
b4.grid(row=2,column=1)
clear=Button(window, text="CLEAR",font=("Comic Sans", 20, "bold"),command=clear)
clear.grid(row=3,column=0,columnspan=2)
window.mainloop()
